import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'

export default function Home() {
  return (
    <>
      <Head>
        <title>Famous | Payment Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='h-[100vh] w-[100vw] flex justify-center ease-linear duration-300 items-center bg-gray-100'>
          <Card />
        </div>
      </div>
    </>
  )
}
